import sys
import io

with io.open(r'd:\P\ok\ok\TRIVEXA\Irfan Project\index.html', 'r', encoding='utf-8') as f:
    lines = f.readlines()

start_idx = 1355
end_idx = 1557

new_lines = [
    '                    <div style="display: flex; gap: 1rem; margin-top: 1.5rem;">\n',
    '                        <button class="btn btn-ghost" onclick="UI.hideModal(\'return-order-modal\')" style="flex: 1; justify-content: center; height: 42px; border-radius: 8px; border: 1px solid var(--glass-border);">Cancel</button>\n',
    '                    </div>\n',
    '                </div>\n',
    '            </div>\n\n',
    '    <!-- Udhaar Modals -->\n',
    '    <!-- Add Customer Modal -->\n',
    '    <div class="modal-overlay" id="udhaar-customer-modal">\n',
    '        <div class="modal-content" style="max-width: 400px;">\n',
    '            <h2 style="margin-bottom: 1.5rem; font-family: \'Outfit\';">Add Wholesale Customer</h2>\n',
    '            <form id="udhaar-customer-form">\n',
    '                <div class="form-group">\n',
    '                    <label>Customer Name</label>\n',
    '                    <input type="text" name="name" required placeholder="e.g. Ali Traders">\n',
    '                </div>\n',
    '                <div class="form-group">\n',
    '                    <label>Contact Number (Optional)</label>\n',
    '                    <input type="text" name="phone" placeholder="03...">\n',
    '                </div>\n',
    '                <div class="form-group">\n',
    '                    <label>Opening Balance (Rs.)</label>\n',
    '                    <input type="number" name="openingBalance" step="0.01" value="0" required>\n',
    '                </div>\n',
    '                <div style="display: flex; gap: 1rem; margin-top: 1.5rem;">\n',
    '                    <button type="button" class="btn btn-ghost" onclick="UI.hideModal(\'udhaar-customer-modal\')" style="flex: 1; justify-content: center;">Cancel</button>\n',
    '                    <button type="submit" class="btn btn-primary" style="flex: 1; justify-content: center;">Save Customer</button>\n',
    '                </div>\n',
    '            </form>\n',
    '        </div>\n',
    '    </div>\n\n',
    '    <!-- Add Transaction Modal -->\n',
    '    <div class="modal-overlay" id="udhaar-transaction-modal">\n',
    '        <div class="modal-content" style="max-width: 400px;">\n',
    '            <h2 style="margin-bottom: 1.5rem; font-family: \'Outfit\';">Add Transaction</h2>\n',
    '            <form id="udhaar-transaction-form">\n',
    '                <input type="hidden" name="customerId">\n',
    '                <div class="form-group">\n',
    '                    <label>Type</label>\n',
    '                    <select name="type" required>\n',
    '                        <option value="credit">Sale (Credit given to customer)</option>\n',
    '                        <option value="payment">Payment Received</option>\n',
    '                    </select>\n',
    '                </div>\n',
    '                <div class="form-group">\n',
    '                    <label>Amount (Rs.)</label>\n',
    '                    <input type="number" name="amount" step="0.01" min="0.01" required>\n',
    '                </div>\n',
    '                <div class="form-group">\n',
    '                    <label>Description / Note</label>\n',
    '                    <input type="text" name="note" placeholder="e.g. Paid in cash">\n',
    '                </div>\n',
    '                <div style="display: flex; gap: 1rem; margin-top: 1.5rem;">\n',
    '                    <button type="button" class="btn btn-ghost" onclick="UI.hideModal(\'udhaar-transaction-modal\')" style="flex: 1; justify-content: center;">Cancel</button>\n',
    '                    <button type="submit" class="btn btn-primary" style="flex: 1; justify-content: center;">Save Transaction</button>\n',
    '                </div>\n',
    '            </form>\n',
    '        </div>\n',
    '    </div>\n\n',
    '    <!-- View Details Modal -->\n',
    '    <div class="modal-overlay" id="udhaar-details-modal">\n',
    '        <div class="modal-content" style="max-width: 500px;">\n',
    '            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;">\n',
    '                <h2 style="margin: 0; font-family: \'Outfit\';" id="udhaar-detail-name">Customer Name</h2>\n',
    '                <button class="btn btn-ghost" onclick="UI.hideModal(\'udhaar-details-modal\')"><i class="fas fa-times"></i></button>\n',
    '            </div>\n',
    '            <div style="margin-bottom: 1rem; padding: 1rem; background: var(--bg-card); border-radius: 8px; border: 1px solid var(--glass-border); display: flex; justify-content: space-between;">\n',
    '                <div>\n',
    '                    <span style="font-size: 0.75rem; color: var(--text-muted); text-transform: uppercase;">Balance Due</span>\n',
    '                    <div style="font-size: 1.25rem; font-weight: 700; color: var(--accent-danger);" id="udhaar-detail-balance">Rs. 0</div>\n',
    '                </div>\n',
    '                <div>\n',
    '                    <span style="font-size: 0.75rem; color: var(--text-muted); text-transform: uppercase;">Contact</span>\n',
    '                    <div style="font-weight: 600;" id="udhaar-detail-contact">-</div>\n',
    '                </div>\n',
    '            </div>\n',
    '            <h3 style="font-size: 1rem; margin-bottom: 0.5rem;">Transaction History</h3>\n',
    '            <div style="max-height: 250px; overflow-y: auto; border: 1px solid var(--glass-border); border-radius: 8px;">\n',
    '                <table style="margin: 0;">\n',
    '                    <thead>\n',
    '                        <tr>\n',
    '                            <th>Date</th>\n',
    '                            <th>Type</th>\n',
    '                            <th>Amount</th>\n',
    '                            <th>Note</th>\n',
    '                        </tr>\n',
    '                    </thead>\n',
    '                    <tbody id="udhaar-detail-history">\n',
    '                    </tbody>\n',
    '                </table>\n',
    '            </div>\n',
    '        </div>\n',
    '    </div>\n\n',
    '    <script src="js/qrcode.min.js"></script>\n',
    '    <script src="js/store.js?v=4"></script>\n',
    '    <script src="js/ui.js?v=4"></script>\n',
    '    <script src="js/dashboard.js?v=4"></script>\n',
    '    <script src="js/analytics.js?v=4"></script>\n',
    '    <script src="js/ledger.js?v=4"></script>\n',
    '    <script src="js/inventory.js?v=4"></script>\n',
    '    <script src="js/wintercollection.js?v=4"></script>\n',
    '    <script src="js/accessories.js?v=4"></script>\n',
    '    <script src="js/pos.js?v=4"></script>\n',
    '    <script src="js/credit.js?v=4"></script>\n',
    '    <script src="js/receipts.js?v=4"></script>\n',
    '    <script src="js/backup.js?v=4"></script>\n',
    '    <script src="js/app.js?v=4"></script>\n\n',
    '    <script>\n',
    '        // Dynamic size options based on article type\n',
    '        function updateSizeOptions(selectId, articleType, currentValue) {\n',
    '            const sizeSelect = document.getElementById(selectId);\n',
    '            if (!sizeSelect) return;\n\n',
    '            let options = [];\n\n',
    '            if (articleType === \'Dress Shirt\') {\n',
    '                options = [\'14\', \'14.5\', \'15\', \'15.5\', \'16\', \'16.5\', \'17\', \'17.5\'];\n',
    '            } else if (articleType === \'Jeans\') {\n',
    '                options = [\'28\', \'30\', \'32\', \'34\', \'36\', \'38\'];\n',
    '            } else {\n',
    '                options = [\'S\', \'M\', \'L\', \'XL\', \'XXL\'];\n',
    '            }\n'
]

lines[start_idx-1:end_idx] = new_lines

with io.open(r'd:\P\ok\ok\TRIVEXA\Irfan Project\index.html', 'w', encoding='utf-8') as f:
    f.writelines(lines)
